# Description of task 
### I observed that a large percentage of the CPDB is composed of ConA homologs.
### To identify all pdbs in the database with similarity to ConA,
### I'll TM-align each one to either pro-ConA (2FMD) or ConA (2CNA)

In [1]:
import pandas as pd
fp = "/home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/sequence_alignment/CPDB_with_uniprotID.csv"
df = pd.read_csv(fp)

In [9]:
df[df['Protein1'] == '2cnaA']

,Protein1,Protein2,tmscore_max,tmscore_cp_max,tmscore_min,tmscore_cp_min,progres_score,cirpin_score,Protein1_sccs,Protein2_sccs,tm_score_min_difference,Protein1_uniprot,Protein2_uniprot
1602,2cnaA,2fmdA,0.48268,0.94310,0.48268,0.94310,0.991433,0.997148,b.29.1.1,b.29.1.0,0.46042,P02866,P42088
1603,2cnaA,1q8oA,0.47097,0.91826,0.46719,0.91088,0.993226,0.996786,b.29.1.1,b.29.1.1,0.44369,P02866,Q8GSD2
1604,2cnaA,1ciwA,0.46969,0.88655,0.46969,0.88655,0.992326,0.996076,b.29.1.1,b.29.1.1,0.41686,P02866,P02872
1605,2cnaA,1bzwA,0.47005,0.88745,0.47005,0.88745,0.992512,0.996899,b.29.1.1,b.29.1.1,0.41740,P02866,P02872
1606,2cnaA,1n47A,0.46058,0.90338,0.46058,0.90338,0.991040,0.994550,b.29.1.1,b.29.1.1,0.44280,P02866,P56625
1607,2cnaA,1fnyA,0.47222,0.90533,0.47222,0.90533,0.992276,0.995318,b.29.1.1,b.29.1.1,0.43311,P02866,Q41159
1608,2cnaA,1g7yA,0.49071,0.90678,0.46463,0.85809,0.990931,0.994389,b.29.1.1,b.29.1.1,0.39346,P02866,P19588
1609,2cnaA,1g8wA,0.46406,0.89485,0.46406,0.89485,0.989858,0.995986,b.29.1.1,b.29.1.1,0.43079,P02866,P05087
1610,2cnaA,1bjqA,0.49483,0.90347,0.46861,0.85493,0.987151,0.994847,b.29.1.1,b.29.1.1,0.38632,P02866,P05045
1611,2cnaA,1uzyA,0.46736,0.90309,0.46547,0.89948,0.990271,0.995087,b.29.1.1,b.29.1.1,0.43401,P02866,Q6YD91
1612,2cnaA,1ax0A,0.46627,0.90587,0.46252,0.89867,0.989849,0.995522,b.29.1.1,b.29.1.1,0.43615,P02866,P16404
1613,2cnaA,1gz9A,0.46732,0.90894,0.46356,0.90169,0.989997,0.995716,b.29.1.1,b.29.1.1,0.43813,P02866,P83410
1614,2cnaA,1hqlA,0.45922,0.88589,0.45922,0.88589,0.992411,0.994285,b.29.1.1,b.29.1.1,0.42667,P02866,Q8W1R6
1615,2cnaA,1dzqA,0.45989,0.88586,0.45989,0.88586,0.992938,0.995466,b.29.1.1,b.29.1.1,0.42597,P02866,Q9FVF8
1616,2cnaA,1fyuA,0.46547,0.90639,0.46173,0.89919,0.989922,0.995892,b.29.1.1,b.29.1.1,0.43746,P02866,P16404
1617,2cnaA,1fatA,0.46395,0.89161,0.46395,0.89161,0.989734,0.995854,b.29.1.1,b.29.1.1,0.42766,P02866,P05087
1618,2cnaA,1lteA,0.46576,0.90516,0.46202,0.89797,0.989771,0.995400,b.29.1.1,b.29.1.1,0.43595,P02866,P16404
1619,2cnaA,1gnzA,0.45508,0.88292,0.45508,0.88292,0.992971,0.993773,b.29.1.1,b.29.1.1,0.42784,P02866,Q8W1R6
1620,2cnaA,1sfyA,0.46708,0.90691,0.46332,0.89970,0.989680,0.995807,b.29.1.1,b.29.1.1,0.43638,P02866,P16404
1621,2cnaA,1dbnA,0.46490,0.91022,0.46114,0.90292,0.993225,0.995131,b.29.1.1,b.29.1.1,0.44178,P02866,P93248
1622,2cnaA,1wbfA,0.46385,0.89742,0.46385,0.89742,0.990524,0.995722,b.29.1.1,b.29.1.1,0.43357,P02866,O24313
1623,2cnaA,2bqpA,0.46806,0.88775,0.46806,0.88775,0.991966,0.994624,b.29.1.1,b.29.1.1,0.41969,P02866,P02867
1624,2cnaA,1wblA,0.46363,0.89204,0.46363,0.89204,0.989643,0.995493,b.29.1.1,b.29.1.1,0.42841,P02866,O24313
1625,2cnaA,1f9kA,0.45760,0.87470,0.45760,0.87470,0.991082,0.993578,b.29.1.1,b.29.1.1,0.41710,P02866,Q9SM56
1626,2cnaA,1fx5A,0.46661,0.87977,0.46105,0.86934,0.992346,0.996163,b.29.1.1,b.29.1.1,0.40829,P02866,P22972
1627,2cnaA,1avbA,0.43078,0.84708,0.43078,0.84708,0.990929,0.990169,b.29.1.1,b.29.1.1,0.41630,P02866,P19329
1628,2cnaA,1ioaA,0.43052,0.85636,0.43052,0.85636,0.989508,0.991742,b.29.1.1,b.29.1.1,0.42584,P02866,Q42460
1629,2cnaA,1bqpA,0.41968,0.69254,0.41968,0.69254,0.551571,0.717380,b.29.1.1,b.29.1.1,0.27286,P02866,P02867
1630,2cnaA,1lgcA,0.42338,0.69704,0.42338,0.69704,0.558426,0.708190,b.29.1.1,b.29.1.1,0.27366,P02866,P04122
1631,2cnaA,1rinA,0.42005,0.69002,0.42005,0.69002,0.551214,0.716469,b.29.1.1,b.29.1.1,0.26997,P02866,P02867
1632,2cnaA,2b7yA,0.41951,0.69434,0.41951,0.69434,0.548202,0.716149,b.29.1.1,NaN,0.27483,P02866,P02871
1633,2cnaA,1ofsA,0.41975,0.69427,0.41975,0.69427,0.545823,0.719738,b.29.1.1,b.29.1.1,0.27452,P02866,P02867
1634,2cnaA,1loaA,0.42367,0.69359,0.42367,0.69359,0.549601,0.714992,b.29.1.1,b.29.1.1,0.26992,P02866,P04122
1635,2cnaA,1lofC,0.42161,0.69183,0.42161,0.69183,0.549306,0.713560,b.29.1.1,b.29.1.1,0.27022,P02866,P04122
1636,2cnaA,1lemA,0.42294,0.69703,0.42294,0.69703,0.548530,0.701007,b.29.1.1,b.29.1.1,0.27409,P02866,P02870
1637,2cnaA,1lgbA,0.42199,0.69455,0.42199,0.69455,0.557108,0.709408,b.29.1.1,b.29.1.1,0.27256,P02866,P04122
1638,2cnaA,1dhkB,0.41325,0.72039,0.41325,0.72039,0.984337,0.976830,b.29.1.1,b.29.1.1,0.30714,P02866,P02873
1639,2cnaA,2a6vA,0.37784,0.67921,0.37784,0.67921,0.964004,0.986922,b.29.1.1,b.29.1.13,0.30137,P02866,Q12396
1640,2cnaA,2a6xA,0.37741,0.68064,0.37741,0.68064,0.964351,0.985683,b.29.1.1,b.29.1.13,0.30323,P02866,Q12396
1641,2cnaA,1r1zA,0.40103,0.74309,0.38625,0.71576,0.976847,0.981779,b.29.1.1,l.1.1.1,0.32951,P02866,Q62902
1642,2cnaA,1viwB,0.41725,0.73357,0.41725,0.73357,0.982116,0.978993,b.29.1.1,b.29.1.1,0.31632,P02866,P02873
1643,2cnaA,1gv9A,0.38097,0.72293,0.38097,0.72293,0.956331,0.987298,b.29.1.1,b.29.1.13,0.34196,P02866,Q62902
1644,2cnaA,1oq1A,0.34411,0.62899,0.34411,0.62899,0.922408,0.976030,b.29.1.1,l.1.1.1,0.28488,P02866,O31524
1645,2cnaA,2a6zA,0.37742,0.69481,0.37742,0.69481,0.963775,0.988834,b.29.1.1,l.1.1.1,0.31739,P02866,P43555
1646,2cnaA,2a6yA,0.38204,0.69262,0.38204,0.69262,0.962433,0.990757,b.29.1.1,b.29.1.13,0.31058,P02866,P43555
1647,2cnaA,1g86A,0.31948,0.47812,0.31948,0.47812,0.975260,0.952291,b.29.1.1,b.29.1.3,0.15864,P02866,Q05315

In [2]:
pdbs = list(pd.concat([df['Protein1'], df['Protein2']]).unique())

In [5]:
def convert_name(name):
    '''Convert name to filename used:
    ex. 1fp3A --> 1FP3_A
    '''
    if pd.isna(name) or len(name) < 5:
        return name
    # Split at position 4 (before chain identifier)
    pdb_code = name[:4].upper()
    chain = name[4:]
    fixed_name = f"{pdb_code}_{chain}.pdb"
    return fixed_name

pdbs_converted = [convert_name(p) for p in pdbs]

In [6]:
import os 
def tmscore(q, t, cp=False):
    '''Run TM-align and get back TM-align score'''
    if cp:
        output = os.popen(f'/home/ubuntu/TM_tools/TMalign {q} {t} -cp')
    else:
        output = os.popen(f'/home/ubuntu/TM_tools/TMalign {q} {t}')
    
    tms = {"tms": []}
    parse_float = lambda x: float(x.split("=")[1].split()[0])
    
    for line in output:
        line = line.rstrip()
        if line.startswith("TM-score"): 
            tms["tms"].append(parse_float(line))
    
    if tms['tms']:
        max_tms = max(tms['tms'])
    else:
        print(f"Warning: tms['tms'] is empty, setting min_tms to 0 for {q}, {t}")
        max_tms = 0
    
    return max_tms

In [23]:
df.head()

,Protein1,Protein2,tmscore_max,tmscore_cp_max,tmscore_min,tmscore_cp_min,progres_score,cirpin_score,Protein1_sccs,Protein2_sccs,tm_score_min_difference,Protein1_uniprot,Protein2_uniprot
0,1fp3A,1vd5A,0.67760,0.67760,0.67760,0.67760,0.939401,0.983705,a.102.1.3,a.102.1.7,0.00000,P17560,Q9RC92
1,1fp3A,1wu4A,0.67768,0.67887,0.67768,0.67887,0.971649,0.990784,a.102.1.3,a.102.1.2,0.00119,P17560,Q9KB30
2,1fp3A,2drqA,0.67558,0.67691,0.67558,0.67691,0.976586,0.990878,a.102.1.3,a.102.1.2,0.00133,P17560,Q9KB30
3,1fp3A,1wu6A,0.67434,0.67558,0.67434,0.67558,0.974675,0.990933,a.102.1.3,a.102.1.2,0.00124,P17560,Q9KB30
4,1fp3A,1hzfA,0.54695,0.55763,0.54695,0.55763,0.911674,0.948243,a.102.1.3,a.102.4.4,0.01068,P17560,P0C0L4

In [28]:

## Calculate TM score between every CPDB pdb and Pro-conA, ConA

import pandas as pd

proconA = '/home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/2FMD_A.pdb'
conA = '/home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/2CNA_A.pdb'
pdb_dir = '/home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/'

# Initialize DataFrame with columns
conA_df = pd.DataFrame(columns=['pdb_id', 'conA_score', 'proconA_score'])

for pdb in pdbs_converted:
    pdb_path = pdb_dir + pdb
    conA_score = tmscore(conA, pdb_path)
    proconA_score = tmscore(proconA, pdb_path)
    # Add row to dataframe
    new_row = pd.DataFrame({
        'pdb_id': [pdb[:-4]], 
        'conA_score': [conA_score], 
        'proconA_score': [proconA_score]
    })
    conA_df = pd.concat([conA_df, new_row], ignore_index=True)
    if len(conA_df) % 100 == 0:
        print(f'Processed {len(conA_df)}')

/tmp/ipykernel_3953487/3958607151.py:20: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  conA_df = pd.concat([conA_df, new_row], ignore_index=True)

Processed 100
Processed 200
Processed 300
Processed 400

Sequence is too short <3!: /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/1TUC_A.pdb
Sequence is too short <3!: /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/1TUC_A.pdb

Warning: tms['tms'] is empty, setting min_tms to 0 for /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/2CNA_A.pdb, /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/1TUC_A.pdb
Warning: tms['tms'] is empty, setting min_tms to 0 for /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/2FMD_A.pdb, /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/1TUC_A.pdb
Processed 500
Processed 600
Processed 700
Processed 800
Processed 900

Sequence is too short <3!: /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/1MH1_A.pdb
Sequence is too short <3!: /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/1MH1_A.pdb

Warning: tms['tms'] is empty, setting min_tms to 0 for /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/2CNA_A.pdb, /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/1MH1_A.pdb
Warning: tms['tms'] is empty, setting min_tms to 0 for /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/2FMD_A.pdb, /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/1MH1_A.pdb

Sequence is too short <3!: /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/1RYF_A.pdb
Sequence is too short <3!: /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/1RYF_A.pdb

Warning: tms['tms'] is empty, setting min_tms to 0 for /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/2CNA_A.pdb, /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/1RYF_A.pdb
Warning: tms['tms'] is empty, setting min_tms to 0 for /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/2FMD_A.pdb, /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/1RYF_A.pdb
Processed 1000
Processed 1100

Sequence is too short <3!: /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/2H7V_A.pdb
Sequence is too short <3!: /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/2H7V_A.pdb

Warning: tms['tms'] is empty, setting min_tms to 0 for /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/2CNA_A.pdb, /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/2H7V_A.pdb
Warning: tms['tms'] is empty, setting min_tms to 0 for /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/2FMD_A.pdb, /home/ubuntu/CIRPIN/cpdb_comparison/foldseek_CPDB_comparison/cpdb_pdbs_2/2H7V_A.pdb
Processed 1200
Processed 1300
Processed 1400
Processed 1500
Processed 1600
Processed 1700
Processed 1800
Processed 1900
Processed 2000
Processed 2100
Processed 2200

In [29]:

### Get list of proconA/conA homologs by filtering for scores > 0.5 using max TM score
conA_homologs = conA_df[(conA_df['conA_score'] > 0.5) | (conA_df['proconA_score'] > 0.5)]['pdb_id'].to_list()
conA_homologs_lower = [name[:4].replace('_', '').lower() + name[-1] for name in conA_homologs]

In [44]:
conA_rows = df[df['Protein1'].isin(conA_homologs_lower) | df['Protein2'].isin(conA_homologs_lower)].index
df_no_conA = df.drop(conA_rows)

In [51]:
len(conA_rows)

876

In [46]:
df_no_conA.head()

,Protein1,Protein2,tmscore_max,tmscore_cp_max,tmscore_min,tmscore_cp_min,progres_score,cirpin_score,Protein1_sccs,Protein2_sccs,tm_score_min_difference,Protein1_uniprot,Protein2_uniprot
0,1fp3A,1vd5A,0.67760,0.67760,0.67760,0.67760,0.939401,0.983705,a.102.1.3,a.102.1.7,0.00000,P17560,Q9RC92
1,1fp3A,1wu4A,0.67768,0.67887,0.67768,0.67887,0.971649,0.990784,a.102.1.3,a.102.1.2,0.00119,P17560,Q9KB30
2,1fp3A,2drqA,0.67558,0.67691,0.67558,0.67691,0.976586,0.990878,a.102.1.3,a.102.1.2,0.00133,P17560,Q9KB30
3,1fp3A,1wu6A,0.67434,0.67558,0.67434,0.67558,0.974675,0.990933,a.102.1.3,a.102.1.2,0.00124,P17560,Q9KB30
4,1fp3A,1hzfA,0.54695,0.55763,0.54695,0.55763,0.911674,0.948243,a.102.1.3,a.102.4.4,0.01068,P17560,P0C0L4

In [49]:
df[(df['tmscore_cp_min'] < 0.5) & (df['tmscore_cp_max'] > 0.5)].head(30)

,Protein1,Protein2,tmscore_max,tmscore_cp_max,tmscore_min,tmscore_cp_min,progres_score,cirpin_score,Protein1_sccs,Protein2_sccs,tm_score_min_difference,Protein1_uniprot,Protein2_uniprot
15,1wzzA,1kktA,0.69636,0.69412,0.48420,0.48250,0.923056,0.971600,a.102.1.2,a.102.2.1,-0.00170,P37696,P31723
16,1wzzA,2h6gB,0.62184,0.56706,0.49232,0.45035,0.906623,0.971099,a.102.1.2,NaN,-0.04197,P37696,P49356
23,2gh4A,1gszA,0.69203,0.69203,0.42755,0.42755,0.847268,0.946206,a.102.1.6,a.102.4.2,0.00000,O34559,P33247
44,1a22A,1yuzA,0.43470,0.52277,0.39885,0.48143,0.728325,0.877635,a.26.1.1,g.41.5.1,0.08258,P01241,P30820
46,1a22A,1yuxA,0.43475,0.52275,0.39886,0.48144,0.719050,0.888328,a.26.1.1,g.41.5.1,0.08258,P01241,P30820
58,1a7dA,2bkcA,0.48649,0.56661,0.40322,0.46935,0.448996,0.773491,a.24.4.1,a.25.1.1,0.06613,P02247,P80725
98,1aluA,1z6oM,0.48509,0.57232,0.41122,0.48968,0.649516,0.944920,a.26.1.1,a.25.1.1,0.07846,P05231,A0A7E5WTY7
113,1ax8A,2g2dA,0.39090,0.57633,0.34010,0.48739,0.685455,0.827762,a.26.1.1,a.25.2.0,0.14729,P41159,P9WP99
114,1ax8A,2nt8A,0.44627,0.56971,0.33863,0.43118,0.671843,0.836236,a.26.1.1,a.25.2.0,0.09255,P41159,Q50EJ2
115,1ax8A,1yuxA,0.54628,0.65000,0.38044,0.45578,0.678258,0.920509,a.26.1.1,g.41.5.1,0.07534,P41159,P30820
116,1ax8A,1rytA,0.49263,0.61238,0.35558,0.44263,0.628496,0.933747,a.26.1.1,g.41.5.1,0.08705,P41159,P24931
132,1axiA,1z6oM,0.40020,0.52510,0.37527,0.49016,0.627274,0.927189,a.26.1.1,a.25.1.1,0.11489,P01241,A0A7E5WTY7
137,1axiA,1yuxA,0.44218,0.52862,0.39648,0.47652,0.687639,0.890430,a.26.1.1,g.41.5.1,0.08004,P01241,P30820
322,1ddnA,2fxaA,0.56714,0.59614,0.46207,0.49089,0.906076,0.956023,a.76.1.1,a.4.5.28,0.02882,P0DJL7,P11065
440,1huwA,1yuzA,0.42403,0.55661,0.36430,0.47864,0.675600,0.853166,a.26.1.1,g.41.5.1,0.11434,P01241,P30820
441,1huwA,1yuxA,0.42378,0.55291,0.36408,0.47603,0.665096,0.868814,a.26.1.1,g.41.5.1,0.11195,P01241,P30820
443,1hwgA,1z6oM,0.39793,0.50645,0.38680,0.49174,0.624622,0.921531,a.26.1.1,a.25.1.1,0.10494,P01241,A0A7E5WTY7
534,1k33A,1wcrA,0.74368,0.71760,0.49263,0.47725,0.676288,0.733786,h.3.2.1,a.7.2.0,-0.01538,P04578,P69791
535,1k33A,2e2aA,0.74145,0.74145,0.48719,0.48719,0.687269,0.693144,h.3.2.1,a.7.2.1,0.00000,P04578,P23532
577,1m62A,1itfA,0.52853,0.53229,0.32607,0.33420,0.752126,0.632421,l.1.1.1,a.26.1.3,0.00813,O95429,P01563
676,1s3qA,1f6fA,0.43174,0.55614,0.37855,0.48626,0.550653,0.968582,a.25.1.1,a.26.1.1,0.10771,O29424,P16038
692,1wu3I,2inpC,0.63133,0.80169,0.35605,0.44058,0.625272,0.889190,a.26.1.3,NaN,0.08453,P01575,Q84AQ4
695,1wu3I,2iyhA,0.63055,0.75911,0.40078,0.48197,0.654413,0.930496,a.26.1.3,a.25.1.2,0.08119,P01575,NaN
786,3hhrA,1z6oM,0.39433,0.51039,0.38324,0.49552,0.621639,0.921650,a.26.1.1,a.25.1.1,0.11228,P01241,A0A7E5WTY7
805,1c7vA,1pvaA,0.69905,0.68897,0.48220,0.47510,0.911024,0.985733,a.39.1.5,a.39.1.4,-0.00710,P04573,P02628
806,1cb1A,2bl0B,0.60307,0.59512,0.37133,0.37138,0.973820,0.972197,a.39.1.1,NaN,0.00005,P02632,P08053
807,1cdmA,1sraA,0.50189,0.50189,0.45836,0.45836,0.739777,0.827352,a.39.1.5,a.39.1.3,0.00000,P62157,P09486
808,1d1oA,2bl0B,0.64884,0.64884,0.38123,0.38123,0.972375,0.977340,a.39.1.1,NaN,0.00000,P02633,P08053
809,1d1oA,1y6wA,0.66766,0.66766,0.40914,0.40914,0.975875,0.982988,a.39.1.1,a.39.1.5,0.00000,P02633,P0DP23
810,1d1oA,1a29A,0.57038,0.57038,0.35388,0.35388,0.971087,0.981234,a.39.1.1,a.39.1.5,0.00000,P02633,P62157

In [55]:
df[df['Protein1_sccs'] == df['Protein2_sccs']]

,Protein1,Protein2,tmscore_max,tmscore_cp_max,tmscore_min,tmscore_cp_min,progres_score,cirpin_score,Protein1_sccs,Protein2_sccs,tm_score_min_difference,Protein1_uniprot,Protein2_uniprot
537,1l3pA,1nlxA,0.62705,0.67800,0.61776,0.66790,0.990689,0.989440,a.24.17.1,a.24.17.1,0.05014,Q40963,P43215
820,1jf0A,1prwA,0.45598,0.52366,0.45598,0.52366,0.973755,0.979054,a.39.1.5,a.39.1.5,0.06768,Q27709,P62157
825,1nyaA,1prwA,0.41997,0.58432,0.41997,0.58432,0.967175,0.979064,a.39.1.5,a.39.1.5,0.16435,P06495,P62157
828,1prwA,2sasA,0.55797,0.68087,0.47243,0.57017,0.963018,0.974341,a.39.1.5,a.39.1.5,0.09774,P62157,P04570
830,1qv0A,1dtlA,0.53604,0.58661,0.53604,0.58661,0.959814,0.970897,a.39.1.5,a.39.1.5,0.05057,Q27709,P09860
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4154,1ti1A,1un2A,0.48785,0.93896,0.48785,0.93896,0.991267,0.995208,c.47.1.13,c.47.1.13,0.45111,P0AEG4,P0AEG4
4155,1un2A,1bq7A,0.51353,0.96431,0.51353,0.96431,0.989165,0.995577,c.47.1.13,c.47.1.13,0.45078,P0AEG4,P0AEG4
4156,1un2A,2b3sA,0.47834,0.91446,0.47593,0.90986,0.985751,0.993427,c.47.1.13,c.47.1.13,0.43393,P0AEG4,P0AEG4
4159,1yzxA,1un2A,0.30365,0.56550,0.30365,0.56550,0.976762,0.971317,c.47.1.13,c.47.1.13,0.26185,Q9Y2Q3,P0AEG4
4160,2b6mA,1un2A,0.50505,0.95804,0.50505,0.95804,0.986281,0.993042,c.47.1.13,c.47.1.13,0.45299,P0AEG4,P0AEG4